import { makeStyles } from "@material-ui/core";

export const subPageStyles = makeStyles(theme => ({
  page: {
    width: "100%",
    height: "100%",
    overflowY: "auto",
    display: "flex",
    flexDirection: "column",
    alignItems: "flex-start",
    minHeight: "calc(100vh - 104px)",
    maxHeight: "calc(100vh - 104px)",
    overflowX: "hidden",
    position: "relative",
  },
  content: {
    width: "100%",
    padding: "45px 40px",
    display: "flex",
    flexDirection: "column",
    height: "fit-content",
  },
  headerTitle: {
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: 40,
    lineHeight: "104.5%",
    marginBottom: 40,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    color: "#181818",
    "& button": {
      marginLeft: 26,
      background: "transparent",
      padding: 0,
      borderRadius: 0,
    },
    "& button img": {
      width: 16,
      height: 18,
    },

    [theme.breakpoints.down("sm")]: {
      fontSize: 30,
    },
    [theme.breakpoints.down("xs")]: {
      fontSize: 20,
    },
  },
  searcher: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "24px 0px 24px 16px",
    maxWidth: 591,
    border: "1px solid #181818",
    boxSizing: "border-box",
    borderRadius: 6,
    marginBottom: 45,
    "& input": {
      fontStyle: "normal",
      fontWeight: 400,
      fontSize: 22,
      height: 22,
      lineHeight: "104.5%",
      color: "#181818",
      border: "none",
      padding: 0,
      outline: "none",
      width: "100%",
      borderRadius: "inherit",
      background: "transparent",
      [theme.breakpoints.down("sm")]: {
        fontSize: 16,
      },
    },
    "& input::placeholder": {
      color: "#181818",
    },
    "& img": {
      width: 28,
      [theme.breakpoints.down("sm")]: {
        width: 24,
      },
    },
    [theme.breakpoints.down("sm")]: {
      padding: "16px 0px 16px 16px",
    },
  },
  tab: {
    marginRight: 24,
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: 18,
    lineHeight: "104.5%",
    color: "#707582",
    opacity: 0.5,
    cursor: "pointer",
  },
  selectedTab: {
    color: "#181818",
    opacity: 1,
  },
  artCards: {
    width: "calc(100% + 20px)",
    marginLeft: -10,
    marginTop: -10,
    marginBottom: 38,
    padding: "10px 5px",
    "& > div": {
      width: "100%",
    },
  },
  artistCards: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    width: "calc(100% + 20px)",
    marginLeft: -10,
    marginTop: -10,
    marginBottom: 38,
    flexWrap: "wrap",
    overflow: "hidden",
    padding: "10px 5px",
    minHeight: 388,
    "& > div": {
      width: "100%",
    },
  },
  collectionCards: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    width: "calc(100% + 20px)",
    marginLeft: -10,
    marginTop: -10,
    marginBottom: 38,
    flexWrap: "wrap",
    overflow: "hidden",
    padding: "10px 5px",
    minHeight: 325,
    "& > div": {
      width: "100%",
    },
  },
  empty: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    width: "100%",
    textAlign: "center",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: 18,
    lineHeight: "104.5%",
  },
  paper: {
    minWidth: 163,
    marginLeft: -15,
    borderRadius: 0,
    marginRop: 5,
    boxShadow: "0px 2px 8px rgba(0, 0, 0, 0.12)",
  },
  title: {
    display: "flex",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: 18,
    lineHeight: "104.5%",
    color: "#000000",
    marginBottom: 20,
    width: "100%",
    justifyContent: "space-between",
    "& span": {
      fontStyle: "normal",
      fontWeight: 800,
      fontSize: 11,
      color: "#707582",
      cursor: "pointer",
    },
  },
  artistCardsHide: {
    maxHeight: 388,
    overflow: "hidden",
  },
  collectionCardsHide: {
    maxHeight: 325,
    overflow: "hidden",
  },
}));
