import { makeStyles } from "@material-ui/core";

export const digitalArtCardStyles = makeStyles(theme => ({
  card: {
    background: "#ffffff",
    boxShadow: "1px 2px 4px rgba(176, 176, 176, 0.24)",
    borderRadius: 16,
    cursor: "pointer",
    minWidth: 276,
    height: "fit-content",
    padding: 16,
  },
  header: {
    display: "flex",
    alignItems: "center",
    width: "100%",
    justifyContent: "space-between",
    "& button": {
      background: "transparent",
      padding: 0,
      borderRadius: 0,
      marginLeft: 20,
    },
    "& button img": {
      width: 18,
    },
  },
  avatar: {
    backgroundColor: "#c4c4c4",
    width: 40,
    minWidth: 40,
    height: 40,
    backgroundRepeat: "no-repeat",
    backgroundSize: "cover",
    backgroundPosition: "center",
    borderRadius: "50%",
    marginRight: 8,
  },
  black: {
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: 14,
    lineHeight: "120%",
    color: "#1a1b1c",
  },
  creatorName: {
    maxWidth: 124,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    lineHeight: 1.2,
  },
  gray: {
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: 14,
    lineHeight: "120%",
    color: "#a4a4a4",
    overflow: "hidden",
    "& span": {
      fontStyle: "normal",
      fontWeight: 800,
      fontSize: 18,
      lineHeight: "104.5%",
      color: "#431ab7",
      marginLeft: 8,
    },
  },
  optionsBtn: {
    width: 18,
    "& img": {
      transform: "rotate(90deg)",
      width: "3px !important",
    },
  },
  media: {
    width: "100%",
    margin: "8px 0px",
    borderRadius: 16,
    height: "auto",
    minHeight: 226,
  },
  fixed: {
    backgroundRepeat: "no-repeat",
    backgroundSize: "cover",
    backgroundPosition: "center",
    backgroundColor: "#c4c4c4",
    height: 226,
    maxHeight: 226,
  },
  info: {
    display: "flex",
    flexDirection: "column",
    "& > div": {
      marginBottom: 8,
      width: "100%",
      textOverflow: "ellipsis",
      overflow: "hidden",
      whiteSpace: "nowrap",
    },
    "& > div:last-child": {
      marginBottom: 8,
    },
  },
  title: {
    fontSize: "18px !important",
    marginBottom: 8,
  },
  auction: {
    display: "flex",
    flexDirection: "column",
    padding: "8px 16px",
    position: "static",
    width: "100%",
    background: "#ddff57",
    borderRadius: 8,
    margin: "0px 0px 16px",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: 14,
    lineHeight: "120%",
    color: "#431ab7",
    "& h5": {
      fontStyle: "normal",
      fontWeight: 800,
      fontSize: 18,
      lineHeight: "104.5%",
      color: "#431ab7",
      margin: "8px 0px 0px",
    },
  },
}));
