import { makeStyles } from "@material-ui/core";

export const badgeCardStyles = makeStyles(theme => ({
  badgeCard: {
    display: "flex",
    background: "#ffffff",
    boxShadow: "0px 2px 8px rgba(0, 0, 0, 0.2)",
    borderRadius: 14,
    padding: "24px 0px 16px 0px",
    width: "calc(50% - 27px)",
    justifyContent: "space-between",
    flexDirection: "column",
    marginBottom: 24,
    marginRight: 24,
    marginTop: 30,
    height: "fit-content",
    cursor: "pointer",
    position: "relative",

    "& .hex.normal": {
      height: "calc(100% - 6px)",
      margin: "3px",
    },
  },
  badgeImage: {
    alignSelf: "flex-end",
    position: "absolute",
    top: "-30px",
    right: "24px",
    width: "56px",
  },
  cardHeader: {
    padding: "0px 24px",
    display: "flex",
    flexDirection: "column",
  },
  cardTitle: {
    display: "flex",
    alignItems: "center",
    marginBottom: 8,
    "& span": {
      fontWeight: 800,
      fontSize: 14,
      lineHeight: "104.5%",
      marginRight: 6,
      color: "black",
    },
  },
  cardTitleIsLocked: {
    color: "black",
    cursor: "pointer",
    position: "relative",
    right: 0,
    bottom: 0,
    "& svg": {
      height: 12,
      width: 9.33,
    },
  },
  cardStats: {
    display: "flex",
    justifyContent: "space-between",
    width: "100%",
    margin: "12px 0",
  },
  cardStatsActions: {
    background: "#181818",
    border: "1px solid #ffffff",
    borderRadius: 18,
    width: 72,
    height: 24,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "0px 12px",
    "& span": {
      cursor: "pointer",
      display: "flex",
      alignItems: "center",
      "& img": {
        width: 12,
      },
    },
    "& span:first-child img": {
      width: 10,
    },
  },
  likes: {
    display: "flex",
    alignItems: "center",
    marginLeft: 14,
    marginRight: 14,
  },
  likesTitle: {
    fontWeight: 400,
    fontSize: 14,
    lineHeight: "120%",
    color: "#707582",
    margin: 0,
    minWidth: "60px",
  },
  likesContent: {
    color: "black",
    marginLeft: 5,
    display: "flex",
    alignItems: "center",
    fontSize: 14,
  },
  badge: {
    fontSize: 11,
    lineHeight: "104.5%",
    textAlign: "center",
    color: "#707582",
    border: "1px solid #707582",
    boxSizing: "border-box",
    borderRadius: 36,
    padding: "7px 12px 6px",
  },
  info: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    borderTop: "1px solid hsla(0, 0%, 0%, 0.05)",
    borderBottom: "1px solid hsla(0, 0%, 0%, 0.05)",
    padding: "16px 24px 8px 24px",
  },
  infoCreator: {
    display: "flex",
    alignItems: "center",
  },
  infoCreatorAvatar: {
    border: "1.5px solid #ffffff",
    borderRadius: 24,
    width: 32,
    height: 32,
    marginRight: 8,
    backgroundRepeat: "no-repeat",
    backgroundSize: "contain",
    backgroundPosition: "center",
  },
  infoCreatorName: {
    fontWeight: 400,
    fontSize: 14,
    lineHeight: "120%",
    margin: 0,
    color: "#707582",
  },
  totalSupply: {
    fontWeight: 400,
    fontSize: 14,
    lineHeight: "120%",
    textAlign: "right",
    color: "#707582",
    "& span": {
      color: "black",
      marginLeft: 5,
    },
  },
  infoBottom: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "16px 24px 0px",
    "& div": {
      fontWeight: 400,
      fontSize: 14,
      lineHeight: "120%",
      color: "#707582",
      "& span": {
        color: "black",
        margin: "0px 5px",
      },
    },
  },
}));
