import { makeStyles } from "@material-ui/core";

export const createPostModalStyles = makeStyles(() => ({
  root: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
  },
  postModalContent: {
    backgroundColor: "#ffffff",
    padding: 40,
    width: 892,
    borderRadius: 16,
    maxWidth: "85vw",
    maxHeight: "85vh",
    overflow: "auto",
    outline: "none",
  },
  closeButton: {
    display: "flex",
    justifyContent: "flex-end",
    cursor: "pointer",
  },
  titleCommunitiesModal: {
    fontSize: 24,
    fontWeight: 800,
    color: "rgb(8, 24, 49)",
  },
  firstRowPost: {
    marginTop: 45,
    marginBottom: 20,
  },
  gridSecondRowCreatePost: {
    marginBottom: 35,
  },
  infoHeaderCommunitiesModal: {
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: 18,
    lineHeight: "104.5%",
    color: "#181818",
    display: "flex",
    alignItems: "center",
  },
  addVideoButton: {
    fontWeight: 400,
    fontSize: 14,
    height: 49,
    lineHeight: "120%",
    color: "#727f9a",
    padding: 16,
    background: "#f7f9fe",
    border: "1px solid #e0e4f3",
    boxSizing: "border-box",
    borderRadius: 16,
    marginTop: 8,
  },
  addVideoButtonDisabled: {
    display: "none",
  },
  infoHeaderCommunitiesModalInAddVideoButton: {
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: 14,
    color: "#727f9a",
    float: "left",
    marginRight: 10,
  },
  tooltipHeaderInfo: {
    verticalAlign: "top",
    marginLeft: 2,
    width: 14,
    height: 14,
    transform: "translateY(-5px)",
  },
  hashtagInput: {
    background: "#f7f9fe",
    border: "1px solid #e0e4f3",
    boxSizing: "border-box",
    borderRadius: 16,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "0px 15px",
    height: 49,
    marginTop: 8,
    "& img": {
      height: 10,
      width: 10,
      cursor: "pointer",
    },
    "& input": {
      border: "none",
      padding: 0,
      margin: 0,
      background: "transparent",
      borderRadius: 0,
      height: "auto",
      outline: "none",
      fontSize: 14,
      color: "#727f9a",
    },
  },
  hashtagsRow: {
    marginTop: 10,
    display: "flex",
    alignItems: "center",
    marginRight: 20,
  },
  hashtagPillFilled: {
    color: "white",
    backgroundColor: "black",
    borderColor: "black",
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: 14.5,
    textAlign: "center",
    padding: "6px 12px",
    borderRadius: 36,
    marginRight: 6,
    cursor: "pointer",
  },
  hashtagPill: {
    fontStyle: "normal",
    fontWeight: 400,
    fontSize: 14.5,
    textAlign: "center",
    color: "#949bab",
    padding: "6px 12px",
    borderRadius: 36,
    border: "1px solid #949bab",
    marginRight: 6,
    cursor: "pointer",
  },
  flexRowInputsCommunitiesModal: {
    display: "flex",
  },
  infoIconCommunitiesModal: {
    width: 12,
    height: 12,
    marginLeft: 3,
    marginTop: -3,
  },
  optionsContainer: {
    display: "flex",
    alignItems: "center",
    marginTop: 22,
  },
  optionButtonsSmall: {
    background: "linear-gradient(97.4deg, #23d0c6 14.43%, #00cc8f 85.96%)",
    width: 40,
    height: 24,
    display: "flex",
    padding: 2,
    borderRadius: 15,
  },
  optionButton: {
    borderRadius: 16,
    backgroundColor: "transparent",
    width: 16,
    padding: 0,
    height: 20,
  },
  optionButtonSelected: {
    borderRadius: 16,
    backgroundColor: "white",
    width: 20,
    padding: 0,
    height: 20,
    boxShadow: "0px 3px 8px rgba(0, 0, 0, 0.15), 0px 3px 1px rgba(0, 0, 0, 0.06)",
  },
  optionsLabel: {
    fontWeight: 800,
    fontSize: 14,
    lineHeight: "104.5%",
    color: "#707582",
    marginLeft: 2,
  },
  shareOptions: {
    marginTop: 10,
    display: "flex",
    alignItems: "center",
    cursor: "pointer",
    "& > div > span": {
      padding: 0,
      marginRight: 8,
    },
    "& > div span": {
      backgroundImage: "linear-gradient(97.4deg, #29e8dc 14.43%, #03eaa5 79.45%)",
      background: "linear-gradient(97.4deg, #29e8dc 14.43%, #03eaa5 79.45%)",
      color: "#29e8dc",
      "-webkit-background-clip": "text",
      backgroundClip: "text",
    },
    "& > div label": {
      fontStyle: "normal",
      fontWeight: 400,
      fontSize: 14,
      marginRight: 24,
      whiteSpace: "nowrap",
      cursor: "pointer",
    },
  },
  buttons: {
    display: "flex",
    alignItems: "center",
    justifyContent: "flex-end",
    justifySelf: "flex-end",
    marginTop: 35,
    "& button": {
      textTransform: "capitalize",
      fontSize: 16,
      lineHeight: "21px",
      textAlign: "center",
      letterSpacing: "-0.02em",
      borderRadius: 10,
      padding: "8px 26px",
    },
    "& button:first-child": {
      color: "#151414",
      border: "2px solid #707582",
      boxSizing: "border-box",
      background: "white",
      marginRight: 24,
    },
  },
}));
